#Intro and asking for user name
print("Hello and welcome to the ultimate solar system quiz.")
print("We will be launching across the solar system learning about each planet")
name = input("But first what is your name?")

print(r"       \\=====\\ "                                      )
print(r"        \\      \\  "                                   )                                                                                             
print(r"        \\ {   }  \\  "                                 )                                                                                              
print(r"        \\           \\  "                              )                                                                                              
print(r"         ================   "                           )                                                                                                 
print(r"          \\             \\   "                         )                                                                                   
print(r"           \\             \\   "                        )                                                                                                                                
print(r"            \\     // \\   \\   "                       )                                                                                                                        
print(r"             \\   {{   }}   \\   "                      )                                                                                                                                   
print(r"              \\   {{    }}  \\   "                     )                                                                                                                                    
print(r"               \\   {{   }}   \\   "                    )                                                                                                                                  
print(r"                \\    \\ //    \\   "                   )                                                                                                                                      
print(r"                 \\             \\   "                  )                                                                                                                                       
print(r"                  \\             \\   "                 )                                                                                                                                     
print(r"                   \\=============\\  "                 )                                                                                                                                        
print(r"                    ||              \\   "              )                                                                                                                                     
print(r"                    ||                \\    "           )                                                                                                                                       
print(r"                    ||  VqpqpqpqpqpqV   \\    "         )                                                                                                                                        
print(r"                    || VqpqpqpqqpqpqpqpV  \\    "       )                                                                                                                                         
print(r"                    || VqpqpqpqpqpqpqpqpqV  \\    "     )                                                                                                                                        
print(r"                    ||  VqpqpqpqpqpqpqpqpqpV  \\    "   )                                                                                                                                           
print(r"                        VqpqpqpqpqpqpqpqpqpqV        "  )                                                                                                                                             
print(r"                          VqpqpqpqqpqpqpqpqpqW        " )                                                                                                                                            
print(r"                            WqpqpqpqpqpqpqpqW          ")                                                                                                                                                
print(r"                               WqpqpqpqpqpqV           ")                                                                                                                                                 
print(r"                                 VqpqpqpqpW            ")                                                                                                                    
print(r"                                    WqpqpqW           " )
print(r"                                       WqppW         "  )
print(r"                                           W       "    )
