print("       \-----\ " )
print("        \      \  "                                  )                                                                                             
print("        \ {   }  \  "                                )                                                                                              
print("        \           \  "                              )                                                                                              
print("         ---------------   "                          )                                                                                                 
print("          \             \   "                         )                                                                                   
print("           \             \   "                        )                                                                                                                                
print("            \      / \    \   "                       )                                                                                                                        
print("             \    {   }    \   "                      )                                                                                                                                   
print("              \    {    }   \   "                     )                                                                                                                                    
print("               \    {   }    \   "                    )                                                                                                                                  
print("                \     \ /     \   "                   )                                                                                                                                      
print("                 \             \   "                  )                                                                                                                                       
print("                  \             \   "                 )                                                                                                                                     
print("                   \ ____________\  "                 )                                                                                                                                        
print("                    |              \   "               )                                                                                                                                     
print("                    |                \    "            )                                                                                                                                       
print("                    |  {    \    \ }   \    "          )                                                                                                                                        
print("                    |  {  \ \        }   \    "        )                                                                                                                                         
print("                    | {\      \    \    }  \    "      )                                                                                                                                        
print("                    |  { \    \ \    \   }   \    "    )                                                                                                                                           
print("                    \ \ {   \  \ \        }            "  )                                                                                                                                             
print("                         {\  \ \  \      }             " )                                                                                                                                            
print("                           { \   \      }              ")                                                                                                                                                
print("                              {     \   }               ")                                                                                                                                                 
print("                                {       }                ")                                                                                                                    
print("                                   {   }  ")